---
- hosts: sde
  roles:
  - role: desktop
  - role: user
  - role: git
  - role: oracle-jdk
    java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'
  - role: docker
    docker_group_members:
      - dremy
  - role: vscode
    users:
      - username: dremy
        visual_studio_code_extensions:
          - bbenoist.vagrant
          - DavidAnson.vscode-markdownlint
          - eamodio.gitlens
          - vscodevim.vim
          - vscoss.vscode-ansible
          - ms-python.python
          - ms-vscode.Go
          - JerryHong.autofilename
          - ms-vscode.csharp
          - jchannon.csharpextensions
          - Leopotam.csharpfixformat
          - Pkief.material-icon-theme
          - PeterJausovec.vscode-docker
          - RoscoP.ActiveFileInStatusBar
        visual_studio_code_settings: {
            "editor.rulers": [80, 100, 120],
            "editor.renderWhitespace": true,
            "files.associations": {
            }
          }
